language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r tests/requirements.txt -e .
script:
- py.test --cov-report term --cov=cssselect
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  user: scrapy
  password:
    secure: UjCXD1ZfqgFcCs4ciPMJDaOQefV3ZOKZ8/dTZxcoaQlE1lr6CkaN6CfTdD50SX2M9uCNWvEcYnvs6U4SizgZ27MYzFWuHonED2alHKy4AtrxCEHD/+lGo9d18cNjLMPDZateX/lITjGiZ4rmYZNuA6wmA4P/bTmdazbSufcmMqY=
  on:
    tags: true
    repo: scrapy/cssselect
    condition: "$TRAVIS_PYTHON_VERSION == '3.6'"
